$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsive:{
        0:{
            items:2.2
        },
        600:{
            items:4.2
        },
        1000:{
            items:6.2
        }
    }
});